export const exportWordData = [
    {
        "name": "西来峰焦化厂",
        "data": {
            "from": "2024-2-26",
            "to": "2024-3-25",
            "purchaseType": "总量",
            "coalType": [
                "1/3焦煤08120",
                "1/3焦煤20090",
                "1/3焦煤（11灰 0.7硫）",
                "1/3焦煤20105",
                "弱粘煤（04040）",
                "无烟煤（03060）",
                "无烟煤（04080）"
            ],
            "passRate": 29.08,
            "total": 269026.02,
            "details": [
                {
                    "Mt_wgt_val": 12.07,
                    "Ad_pass_rate": 74,
                    "Ad_wgt_val": 11.73,
                    "Vdaf_pass_rate": 0,
                    "Vdaf_wgt_val": 32.89,
                    "Std_pass_rate": 88.12,
                    "Std_wgt_val": 0.7,
                    "g_pass_rate": 100,
                    "g_wgt_val": 93.9,
                    "y_pass_rate": 100,
                    "y_wgt_val": 20.7,
                    "passRate": 0,
                    "total": 28796.68,
                    "coalName": "1/3焦煤08120",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.59,
                    "Ad_pass_rate": 71.83,
                    "Ad_wgt_val": 8.75,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 27.85,
                    "Std_pass_rate": 93.07,
                    "Std_wgt_val": 1.88,
                    "g_pass_rate": 100,
                    "g_wgt_val": 94.66,
                    "y_pass_rate": 100,
                    "y_wgt_val": 21.63,
                    "passRate": 64.9,
                    "total": 22745.86,
                    "coalName": "1/3焦煤20090",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 12.68,
                    "Ad_pass_rate": 20.51,
                    "Ad_wgt_val": 11.16,
                    "Vdaf_pass_rate": 54.71,
                    "Vdaf_wgt_val": 33.97,
                    "Std_pass_rate": 99.29,
                    "Std_wgt_val": 0.53,
                    "g_pass_rate": 100,
                    "g_wgt_val": 94.82,
                    "y_pass_rate": "-",
                    "y_wgt_val": 20.93,
                    "passRate": 5.88,
                    "total": 134636.18,
                    "coalName": "1/3焦煤（11灰 0.7硫）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.58,
                    "Ad_pass_rate": 58.49,
                    "Ad_wgt_val": 10.44,
                    "Vdaf_pass_rate": 57.96,
                    "Vdaf_wgt_val": 29.78,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 1.8,
                    "g_pass_rate": 100,
                    "g_wgt_val": 93.3,
                    "y_pass_rate": 100,
                    "y_wgt_val": 20.49,
                    "passRate": 25.49,
                    "total": 24403.4,
                    "coalName": "1/3焦煤20105",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 17.35,
                    "Ad_pass_rate": 90.11,
                    "Ad_wgt_val": 3.65,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 36.44,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.26,
                    "g_pass_rate": "-",
                    "g_wgt_val": "-",
                    "y_pass_rate": "-",
                    "y_wgt_val": "-",
                    "passRate": 90.11,
                    "total": 48393.02,
                    "coalName": "弱粘煤（04040）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 12.68,
                    "Ad_pass_rate": 58.86,
                    "Ad_wgt_val": 5.96,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 7.67,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.24,
                    "g_pass_rate": "-",
                    "g_wgt_val": "-",
                    "y_pass_rate": "-",
                    "y_wgt_val": "-",
                    "passRate": 58.86,
                    "total": 8808.16,
                    "coalName": "无烟煤（03060）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 13.52,
                    "Ad_pass_rate": 61.04,
                    "Ad_wgt_val": 7.79,
                    "Vdaf_pass_rate": 64.84,
                    "Vdaf_wgt_val": 9.43,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.24,
                    "g_pass_rate": "-",
                    "g_wgt_val": "-",
                    "y_pass_rate": "-",
                    "y_wgt_val": "-",
                    "passRate": 43.42,
                    "total": 1242.72,
                    "coalName": "无烟煤（04080）",
                    "type": "精煤"
                }
            ]
        }
    },
    {
        "name": "巴能公司焦化厂",
        "data": {
            "from": "2024-2-26",
            "to": "2024-3-25",
            "purchaseType": "总量",
            "coalType": [
                "弱粘煤（04040）",
                "1/3焦煤20105",
                "1/3焦煤",
                "蒙古3#精煤",
                "1/3焦洗精煤",
                "无烟煤（03060）",
                "1/3焦煤（20105）",
                "1/3焦煤20090",
                "主焦18110",
                "蒙古1/3焦煤"
            ],
            "passRate": 21.92,
            "total": 72396.33,
            "details": [
                {
                    "Mt_wgt_val": 18.49,
                    "Ad_pass_rate": 65.39,
                    "Ad_wgt_val": 3.76,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 36.03,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.25,
                    "g_pass_rate": "-",
                    "g_wgt_val": "-",
                    "y_pass_rate": "-",
                    "y_wgt_val": "-",
                    "passRate": 65.39,
                    "total": 14432.75,
                    "coalName": "弱粘煤（04040）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.24,
                    "Ad_pass_rate": 75.94,
                    "Ad_wgt_val": 10.38,
                    "Vdaf_pass_rate": 33.99,
                    "Vdaf_wgt_val": 30.29,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 1.69,
                    "g_pass_rate": 100,
                    "g_wgt_val": 92.25,
                    "y_pass_rate": 100,
                    "y_wgt_val": 22.12,
                    "passRate": 24.39,
                    "total": 14490.6,
                    "coalName": "1/3焦煤20105",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.36,
                    "Ad_pass_rate": 0,
                    "Ad_wgt_val": 11.43,
                    "Vdaf_pass_rate": 0,
                    "Vdaf_wgt_val": 33.5,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.53,
                    "g_pass_rate": 100,
                    "g_wgt_val": 95.06,
                    "y_pass_rate": 100,
                    "y_wgt_val": 22.52,
                    "passRate": 0,
                    "total": 12132.75,
                    "coalName": "1/3焦煤",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 7.49,
                    "Ad_pass_rate": 2.68,
                    "Ad_wgt_val": 11.06,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 25.74,
                    "Std_pass_rate": 96.62,
                    "Std_wgt_val": 0.64,
                    "g_pass_rate": 74.58,
                    "g_wgt_val": 80.53,
                    "y_pass_rate": "-",
                    "y_wgt_val": 14.52,
                    "passRate": 2.68,
                    "total": 22450.8,
                    "coalName": "蒙古3#精煤",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 7.97,
                    "Ad_pass_rate": 61.71,
                    "Ad_wgt_val": 10.28,
                    "Vdaf_pass_rate": 78.41,
                    "Vdaf_wgt_val": 34.32,
                    "Std_pass_rate": 59.88,
                    "Std_wgt_val": 0.74,
                    "g_pass_rate": 100,
                    "g_wgt_val": 88.31,
                    "y_pass_rate": "-",
                    "y_wgt_val": 16.15,
                    "passRate": 0,
                    "total": 2357.45,
                    "coalName": "1/3焦洗精煤",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 12.29,
                    "Ad_pass_rate": 58.43,
                    "Ad_wgt_val": 5.89,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 7.36,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.22,
                    "g_pass_rate": "-",
                    "g_wgt_val": "-",
                    "y_pass_rate": "-",
                    "y_wgt_val": "-",
                    "passRate": 58.43,
                    "total": 1896.85,
                    "coalName": "无烟煤（03060）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.02,
                    "Ad_pass_rate": 100,
                    "Ad_wgt_val": 10.21,
                    "Vdaf_pass_rate": 0,
                    "Vdaf_wgt_val": 34.36,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 1.89,
                    "g_pass_rate": 0,
                    "g_wgt_val": 77.29,
                    "y_pass_rate": 0,
                    "y_wgt_val": 15,
                    "passRate": 0,
                    "total": 1972.85,
                    "coalName": "1/3焦煤（20105）",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 11.52,
                    "Ad_pass_rate": 43.81,
                    "Ad_wgt_val": 9.89,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 27.12,
                    "Std_pass_rate": 81.39,
                    "Std_wgt_val": 1.91,
                    "g_pass_rate": 100,
                    "g_wgt_val": 93.92,
                    "y_pass_rate": 100,
                    "y_wgt_val": 22.77,
                    "passRate": 36.42,
                    "total": 1876.15,
                    "coalName": "1/3焦煤20090",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 10.78,
                    "Ad_pass_rate": 49.89,
                    "Ad_wgt_val": 11.08,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 26.68,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 1.66,
                    "g_pass_rate": 100,
                    "g_wgt_val": 92.28,
                    "y_pass_rate": 100,
                    "y_wgt_val": 21.97,
                    "passRate": 49.89,
                    "total": 566.35,
                    "coalName": "主焦18110",
                    "type": "精煤"
                },
                {
                    "Mt_wgt_val": 7,
                    "Ad_pass_rate": 100,
                    "Ad_wgt_val": 9.59,
                    "Vdaf_pass_rate": 100,
                    "Vdaf_wgt_val": 34.67,
                    "Std_pass_rate": 100,
                    "Std_wgt_val": 0.6,
                    "g_pass_rate": 100,
                    "g_wgt_val": 89,
                    "y_pass_rate": "-",
                    "y_wgt_val": 19.5,
                    "passRate": 100,
                    "total": 219.78,
                    "coalName": "蒙古1/3焦煤",
                    "type": "精煤"
                }
            ]
        }
    },
    {
        "name": "蒙西焦化厂",
        "data": {
            "from": "2024-2-26",
            "to": "2024-3-25",
            "purchaseType": "总量",
            "coalType": [],
            "passRate": 0,
            "total": 0,
            "details": []
        }
    }
];